#!/bin/sh

DIR=`pwd`

TESTS="count1 countnode1 delete1 dtd1 dtd2 findfile1 hello1 look1 noindent1 schema sel1 sort1 sum1 tab1 table1 table2 table3 xsl-param1 xsl-sum1"

cd ../examples

for i in $TESTS
do
    ./${i} > /tmp/xmlstarlet.$$ 2>/dev/null
    diff -q /tmp/xmlstarlet.$$ results/${i}.out
    if [ $? != "0" ]
    then
	    echo "test $i - FAILED"
    else
	    echo "test $i - success"
    fi
    rm -f /tmp/xmlstarlet.$$
done

cd ${DIR}

