#! /bin/sh

XMLSTARLET=$1
STAR_NAME=`echo xml | sed "$transform"`

{
echo ""
echo ""
echo "                                           XMLSTARLET USER'S GUIDE"
echo ""
echo "                                  see also http://xmlstar.sourceforge.net/"
echo ""
echo ""

echo ""
echo ""
echo "1. BASIC COMMAND LINE OPTIONS"
echo "===================================================="
echo ""
echo "$STAR_NAME"
"$XMLSTARLET" --help

echo ""
echo ""
echo ""
echo "2. Select/Query XML documents"
echo "===================================================="
echo ""
echo "$STAR_NAME sel --help"
"$XMLSTARLET" sel --help

echo ""
echo ""
echo ""
echo "3. Editing XML documents"
echo "===================================================="
echo ""
echo "$STAR_NAME ed --help"
"$XMLSTARLET" ed --help

echo ""
echo ""
echo ""
echo "4. Using XSLT to transform XML documents"
echo "===================================================="
echo ""
echo "$STAR_NAME tr --help"
"$XMLSTARLET" tr --help

echo ""
echo ""
echo ""
echo "5. Formatting XML documents"
echo "===================================================="
echo ""
echo "$STAR_NAME fo --help"
"$XMLSTARLET" fo --help

echo ""
echo ""
echo ""
echo "6. Validating XML documents"
echo "===================================================="
echo ""
echo "$STAR_NAME val --help"
"$XMLSTARLET" val --help

echo ""
echo ""
echo ""
echo "7. Displaying structure of XML documents"
echo "===================================================="
echo ""
echo "$STAR_NAME el --help"
"$XMLSTARLET" el --help

echo ""
echo ""
echo ""
echo ""
echo "8. Escape/Unescape special XML characters"
echo "===================================================="
echo ""
echo "$STAR_NAME esc --help"
"$XMLSTARLET" esc --help

echo ""
echo ""
echo ""
echo ""
echo "9. List directory as XML"
echo "===================================================="
echo ""
echo "$STAR_NAME ls --help"
"$XMLSTARLET" ls --help

echo ""
echo ""
echo ""
echo ""
echo "10. XML canonicalization"
echo "===================================================="
echo ""
echo "$STAR_NAME c14n --help"
"$XMLSTARLET" c14n --help

echo ""
echo ""
echo ""
echo ""
echo "11. Convert XML into PYX format (based on ESIS - ISO 8879)"
echo "===================================================="
echo ""
echo "$STAR_NAME pyx --help"
"$XMLSTARLET" pyx --help

echo ""
echo ""
echo ""
echo ""
echo "12. Examples:"
echo "===================================================="
echo ""
echo "Input1"
echo "examples/xml/table.xml"
echo ""
cat "$srcdir"/examples/xml/table.xml
echo ""
echo ""
echo "Input2"
echo "examples/xml/tab-obj.xml"
echo ""
cat "$srcdir"/examples/xml/tab-obj.xml
echo ""
echo ""
echo "Input3"
echo "examples/html/hello1.html"
echo ""
cat "$srcdir"/examples/html/hello1.html
echo ""
echo ""
echo "Input4"
echo "examples/sgml/docbook1.sgml"
echo ""
cat "$srcdir"/examples/sgml/docbook1.sgml
echo ""
echo ""
echo "Stylesheet1"
echo "examples/xsl/sum1.xsl"
echo ""
cat "$srcdir"/examples/xsl/sum1.xsl
echo ""
echo ""
echo "Stylesheet2"
echo "examples/xsl/hello1.xsl"
echo ""
cat "$srcdir"/examples/xsl/hello1.xsl
echo ""
echo ""
echo "Stylesheet3"
echo "examples/xsl/param1.xsl"
echo ""
cat "$srcdir"/examples/xsl/param1.xsl
echo ""
echo ""

echo ""

for eg in "$srcdir"/examples/*[0-9]
do
	if [ -x "$eg" ]
	then
		echo "Command:"
		sed -e '/^#!/d' "$eg"
		echo "Result Output:"
		cat "$srcdir"/examples/results/`basename $eg`.out
		echo ""
		echo ""
	fi
done

echo ""
} | sed -e "s#\./xmlstarlet#$STAR_NAME#g; s#\([./]\)*xml #$STAR_NAME #g"


