#!/bin/sh
# check error messages on lines past 2^16

SEDLINUM_PROG='s/^\([^:][^:]*:[0-9]\{4\}\)[0-9]\.[0-9][0-9]*:.*$/\1x/p'

xmldoc()
{
    BAD="$1"
    DOCTYPE="$2"

    echo '<?xml version="1.0"?>'
    [ -n "$DOCTYPE" ] && echo "$DOCTYPE"
    echo '<root>'
    ${AWK:-awk} 'BEGIN{for(i=0; i < 69999; i++) print ""}' < /dev/null
    echo "$BAD"
    echo '</root>'
}
