#!/bin/sh
./xmlstarlet ed \
    -u /xml/table/rec/@id -x .+1 \
    -a /xml/table -t elem -n highest-record -v '' \
    -u /xml/highest-record -x '/xml/table/rec[numField=math:max(../rec/numField)]' \
    xml/table.xml
