#!/bin/sh
echo '<x/>' | ../xml sel -T -t -i 'true()'  -o yes -n --else -o no -n -b -o all -n
echo '<x/>' | ../xml sel -T -t -i 'false()' -o yes -n --else -o no -n -b -o all -n
echo '<x/>' | ../xml sel -T -t -i 'false()' -o yes -n --elif 'true()' -o maybe -n --else -o no -n -b -o all -n
